# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box_url = "http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210.box"
  config.vm.synced_folder "../environnements/", "/tmp/vagrant-puppet/environnements"

  config.vm.define :lab_devops do |lab_devops|
    lab_devops.vm.box = "lab_devops"
    lab_devops.vm.hostname = "ip-172-31-0-24.eu-west-1.compute.internal"

    lab_devops.vm.network :forwarded_port, guest: 8080, host: 8080
    lab_devops.vm.network :forwarded_port, guest: 80, host: 8181

    lab_devops.vm.provision :puppet do |puppet|
      puppet.puppet_node = lab_devops.vm.hostname
      puppet.manifests_path = "../manifests"
      puppet.module_path = "../modules"
      puppet.manifest_file  = "site.pp"
    end
  end

end
